[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"  # ✅ Corrected

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
