[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai", "@supabase/supabase-js"]

[[redirects]]
  from = "/api/*"
- to = "./.netlify/functions/:splat"
+ to = "/.netlify/functions/:splat"

  status = 200
