[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

# Optional: only if you need rewrites for nicer frontend URLs
# Example: redirect /api/chat to /.netlify/functions/chat
[[redirects]]
  from = "/api/:splat"
  to = "/.netlify/functions/:splat"
  status = 200
