[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "functions/*"
  to = "functions/:splat"
  status = 200
  force = true
